name: Scrape ETF Data

on:
  schedule:
    # Run every 3 minutes during market hours (9:15 AM - 3:30 PM IST)
    # IST = UTC+5:30, so 9:15 AM IST = 3:45 AM UTC, 3:30 PM IST = 10:00 AM UTC
    - cron: '*/3 3-10 * * 1-5'  # Every 3 minutes, 3:45 AM - 10:00 AM UTC, Mon-Fri

  workflow_dispatch:  # Allow manual trigger from GitHub UI

  push:
    branches:
      - main  # Run on push to main branch (optional - for testing)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scrapers/run_scraper.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/*.csv data/*.json data/*.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Auto-update ETF data $(date +'%Y-%m-%d %H:%M:%S UTC')"
          git push
