name: Scrape ETF Data

on:
  schedule:
    # Weekdays: Every 3 minutes from 9:15 AM - 6:30 PM IST (3:45-13:00 UTC)
    - cron: '*/3 3-13 * * 1-5'

    # Saturday: Once at 10:00 AM IST (4:30 UTC)
    - cron: '30 4 * * 6'

  workflow_dispatch:  # Manual trigger anytime

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scrapers/run_scraper.py

      - name: Commit generated files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/
          git commit -m "Update ETF data - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
